### ISSUE TITLE
[CTD] when killed by Skeleton on Bop grass

### ISSUE THREAD

**Issue by drakray** [NightKosh/Gravestone-mod-Graves#235]
https://pastebin.com/JBTszCRj

**Comment by FiveEYZ** [comment]
https://gist.github.com/FiveEYZ/fcf1aa1fbfd6dfacd6160863c7f6e73e

**Comment by FiveEYZ** [comment]
Wanted to add that a player was on fire, as soon as he hit 0 hearts he got disconnected from the server, and that gist is what gets printed on the server.

when he got online again he was at the same location where he would have died, but he had full health and empty inventory.

**Comment by FiveEYZ** [comment]
this is becoming a major issue, people keep dying and when they do it crashes the server. 

also tried to remove the mod from the server (and wait until it was fixed), but apparently that will prevent players from logging in because the the grave expect a user and will just timeout anyone trying to login.

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-graves/files/2458100

https://minecraft.curseforge.com/projects/gravestone-mod-graves/files/2458111
